# Generated by Django 6.0.5 on 2026-05-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='list_type',
            field=models.CharField(choices=[('erledigungen', 'Erledigungen'), ('besorgungen', 'Besorgungen')], default='erledigungen', max_length=20),
        ),
    ]
