# Generated by Django 6.0.5 on 2026-05-13 12:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0002_shoppingitem_list_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='list_type',
            field=models.CharField(default='erledigungen', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mylist.shoppinglist'),
        ),
    ]
