# Generated by Django 6.0.5 on 2026-05-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylist', '0004_assign_existing_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='list_type',
        ),
    ]
